const express = require("express");
const router = express.Router();
const { getAllCategories } = require("../controlers/categoryControler");
const { createCategory } = require("../controlers/categoryControler");
const { updateCategory } = require("../controlers/categoryControler");
const { deleteCategory } = require("../controlers/categoryControler");
const  isAdmin  = require("../middlewares/admin");
router.get("/categories", getAllCategories);
router.post("/categories", isAdmin, createCategory);
router.put("/categories/:id", isAdmin, updateCategory);
router.delete("/categories/:id", isAdmin, deleteCategory);
module.exports = router;
